# Generated by Django 3.1 on 2020-08-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20200822_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='exit_east_id',
            new_name='exit_east',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='exit_north_id',
            new_name='exit_north',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='exit_south_id',
            new_name='exit_south',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='exit_west_id',
            new_name='exit_west',
        ),
    ]
