# Generated by Django 3.1 on 2020-09-12 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_auto_20200908_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='zone_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='world.zone'),
            preserve_default=False,
        ),
    ]
