# Generated by Django 3.1 on 2020-09-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_auto_20200912_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='zone_id',
            new_name='zone',
        ),
    ]
